"""Functions table updated

Revision ID: 0fc66f569336
Revises: 9cc31cdbbda4
Create Date: 2025-03-15 08:10:02.959802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc66f569336'
down_revision: Union[str, None] = '9cc31cdbbda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('functions', 'created_at')
    # ### end Alembic commands ###
