"""Initial migration

Revision ID: 346d859d226e
Revises: 
Create Date: 2025-03-15 12:39:23.077967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '346d859d226e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('sourceCredentials', sa.JSON(), nullable=True),
    sa.Column('sourceDetails', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('timeSlot', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('camerasAssigned', sa.JSON(), nullable=True),
    sa.Column('saveRecordings', sa.Boolean(), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('otherDetails', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('function_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('avg_people_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('function_recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recording', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('imageUrl', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('otherDetails', sa.JSON(), nullable=True),
    sa.Column('people_model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_model_id'], ['people_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    op.drop_table('function_recordings')
    op.drop_table('function_info')
    op.drop_table('users')
    op.drop_table('people_model')
    op.drop_table('functions')
    op.drop_table('camera_sources')
    # ### end Alembic commands ###
