"""Added Users Table for Admins and moderators

Revision ID: 4495ae908001
Revises: 7162db0f6125
Create Date: 2025-03-14 09:01:55.416792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4495ae908001'
down_revision: Union[str, None] = '7162db0f6125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
