"""user model id optional changed in user

Revision ID: 4ec286a4d240
Revises: 5649fc1d0dd7
Create Date: 2025-02-20 11:05:40.076199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ec286a4d240'
down_revision: Union[str, None] = '5649fc1d0dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_model_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_model_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
