"""add image url in user

Revision ID: 5649fc1d0dd7
Revises: 6ec6c418659d
Create Date: 2025-02-20 00:00:25.626486

"""
from typing import Sequence, Union
import sqlmodel as sa
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5649fc1d0dd7'
down_revision: Union[str, None] = '6ec6c418659d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('imageUrl', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.create_unique_constraint(None, 'user_model', ['role'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_model', type_='unique')
    op.drop_column('user', 'imageUrl')
    # ### end Alembic commands ###
