"""removed fields in usermodel

Revision ID: 6ec6c418659d
Revises: d0c55aeb2fb1
Create Date: 2025-02-19 23:34:12.810284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec6c418659d'
down_revision: Union[str, None] = 'd0c55aeb2fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
