"""Updated Users model and table name and also endpoint

Revision ID: 7162db0f6125
Revises: 4ec286a4d240
Create Date: 2025-03-14 08:54:55.619385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7162db0f6125'
down_revision: Union[str, None] = '4ec286a4d240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('otherDetails', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('imageUrl', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('otherDetails', sa.JSON(), nullable=True),
    sa.Column('people_model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_model_id'], ['people_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_index('role', table_name='user_model')
    op.drop_table('user_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('otherDetails', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('role', 'user_model', ['role'], unique=True)
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('otherDetails', mysql.JSON(), nullable=True),
    sa.Column('user_model_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('imageUrl', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_model_id'], ['user_model.id'], name='user_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('people')
    op.drop_table('people_model')
    # ### end Alembic commands ###
