"""Functions table added

Revision ID: 9cc31cdbbda4
Revises: a7af1d7e1e6d
Create Date: 2025-03-15 07:58:28.326958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9cc31cdbbda4'
down_revision: Union[str, None] = 'a7af1d7e1e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('timeSlot', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('camerasAssigned', sa.JSON(), nullable=True),
    sa.Column('saveRecordings', sa.Boolean(), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('functions')
    # ### end Alembic commands ###
